# Site settings
title: Workshop
email: robert@letsworkshop.com
description: "Frontend design project alerts for picky firms. We find clients that are looking to build an amazing UX and send them to you."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://letsworkshop.com" # the base hostname & protocol for your site
twitter_username: letsworkshop
github_username:  robwco
# Build settings
markdown: kramdown
parse_block_html: true
gems:
  - jemoji
collections:
  bonus:
    output: true
    permalink: /bonus/:name/
  guides:
    output: true

defaults:
  - scope:
      path: ''
      type: 'email'
    values:
      layout: 'page'
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'bonus'
    values:
      layout: 'bonus'
  - scope:
      path: ''
      type: 'product'
    values:
      layout: 'product'