# Site settings
title: Workshop - Get great clients sent to you everyday
email: robert@letsworkshop.com
description: Get over 200+ hand selected freelance web consulting leads sent to your inbox every week 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://letsworkshop.com" # the base hostname & protocol for your site
twitter_username: clientgiantrob
github_username:  robwco
# Build settings
markdown: kramdown
parse_block_html: true