# Site settings
title: Workshop
email: robert@letsworkshop.com
description: "Projects for people who make websites. Every morning Robert finds the top 6 job posts for project-seeking website designers."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://letsworkshop.com" # the base hostname & protocol for your site
twitter_username: clientgiantrob
github_username:  robwco
# Build settings
markdown: kramdown
parse_block_html: true
gems:
  - jemoji
collections:
  bonus:
    output: true
    permalink: /bonus/:name/
  guides:
    output: true

defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'bonus'
    values:
      layout: 'bonus'
  - scope:
      path: ''
      type: 'product'
    values:
      layout: 'product'