- name: "Leads Service"
  offer: "Projects found for you daily"
  permalink: /leads/
  summary: "This is my main service. I send 3+ high-value projects per customer every business day. Extremely limited spots available."
  coming_soon: false
  pic: "./images/workshop-preview-sd.png"

- name: "Where to find clients"
  offer: "Where to find high-paying clients"
  permalink: /find/
  summary: "A complete list of exactly what websites I use to find thousands of potential gigs every year."
  coming_soon: false
  pic: "./images/automation-video-course.png"
  

- name: "Emails that win you clients"
  offer: "Emails that win you clients"
  permalink: /emails/
  summary: "A library of the biggest mistakes made emailing clients, tips on how to avoid them, and examples of successful emails to use instead."
  coming_soon: false
  pic: "./images/etw-field-guide.png"
  