- name: "Leads Service"
  offer: "Lead Service: I find you new projects daily"
  permalink: /leads/
  summary: "This is my main service. I send 3+ high-value projects per customer every month. Extremely limited availability."
  coming_soon: false
  pic: "/images/workshop-preview-sd.png"

- name: "Where to find clients"
  offer: "Where to find high-paying clients"
  permalink: /find/
  summary: "A complete list of exactly what websites I use to find the gigs I sell above: thousands of projects every year."
  coming_soon: false
  pic: "/images/automation-video-course.png"
  

- name: "Emails that win you clients"
  offer: "Emails that win you clients"
  permalink: /emails/
  summary: "A training product with the biggest mistakes freelancers make when emailing clients, plus examples of successful emails to use instead."
  coming_soon: false
  pic: "/images/etw-field-guide.png"
  